//! Instruction set — see nlvm-specs/docs/vm.md § Instruction set.
//! Byte values are this implementation's own encoding; the spec only mandates
//! the mnemonics, operand shapes and stack effects, not concrete opcode numbers.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Opcode {
    Nop = 0,
    Pop = 1,
    Dup = 2,
    Swap = 3,
    DupX1 = 4,

    ConstNull = 10,
    ConstTrue = 11,
    ConstFalse = 12,
    ConstIZero = 13,
    ConstIOne = 14,
    ConstFZero = 15,
    ConstFOne = 16,
    BiPush = 17,
    SiPush = 18,
    Ldc = 19,

    Load = 20,
    Store = 21,
    Load0 = 22,
    Load1 = 23,
    Load2 = 24,
    Load3 = 25,
    Store0 = 26,
    Store1 = 27,
    Store2 = 28,
    Store3 = 29,

    IAdd = 30,
    ISub = 31,
    IMul = 32,
    IDiv = 33,
    IMod = 34,
    INeg = 35,
    IInc = 36,

    FAdd = 40,
    FSub = 41,
    FMul = 42,
    FDiv = 43,
    FMod = 44,
    FNeg = 45,

    I2F = 50,
    F2I = 51,
    I2B = 52,
    B2I = 53,
    ToString = 54,

    CmpEq = 60,
    CmpNe = 61,
    CmpLt = 62,
    CmpGt = 63,
    CmpLe = 64,
    CmpGe = 65,
    CmpThreeWay = 66,
    IsNull = 67,
    IsNonNull = 68,
    Not = 69,

    IfTrue = 70,
    IfFalse = 71,
    Goto = 72,
    GotoW = 73,

    New = 80,
    InstanceOf = 81,
    CheckCast = 82,

    NewArray = 90,
    NewArrayInit = 91,
    ArrayLoad = 92,
    ArrayStore = 93,
    ArrayLength = 94,

    GetField = 100,
    SetField = 101,
    GetStatic = 102,
    SetStatic = 103,

    InvokeStatic = 110,
    InvokeInstance = 111,
    InvokeSpecial = 112,
    InvokeClosure = 113,
    Return = 114,
    ReturnValue = 115,

    StrConcat = 120,

    Throw = 130,
}

impl Opcode {
    pub fn from_u8(byte: u8) -> Option<Self> {
        use Opcode::*;
        let op = match byte {
            0 => Nop,
            1 => Pop,
            2 => Dup,
            3 => Swap,
            4 => DupX1,
            10 => ConstNull,
            11 => ConstTrue,
            12 => ConstFalse,
            13 => ConstIZero,
            14 => ConstIOne,
            15 => ConstFZero,
            16 => ConstFOne,
            17 => BiPush,
            18 => SiPush,
            19 => Ldc,
            20 => Load,
            21 => Store,
            22 => Load0,
            23 => Load1,
            24 => Load2,
            25 => Load3,
            26 => Store0,
            27 => Store1,
            28 => Store2,
            29 => Store3,
            30 => IAdd,
            31 => ISub,
            32 => IMul,
            33 => IDiv,
            34 => IMod,
            35 => INeg,
            36 => IInc,
            40 => FAdd,
            41 => FSub,
            42 => FMul,
            43 => FDiv,
            44 => FMod,
            45 => FNeg,
            50 => I2F,
            51 => F2I,
            52 => I2B,
            53 => B2I,
            54 => ToString,
            60 => CmpEq,
            61 => CmpNe,
            62 => CmpLt,
            63 => CmpGt,
            64 => CmpLe,
            65 => CmpGe,
            66 => CmpThreeWay,
            67 => IsNull,
            68 => IsNonNull,
            69 => Not,
            70 => IfTrue,
            71 => IfFalse,
            72 => Goto,
            73 => GotoW,
            80 => New,
            81 => InstanceOf,
            82 => CheckCast,
            90 => NewArray,
            91 => NewArrayInit,
            92 => ArrayLoad,
            93 => ArrayStore,
            94 => ArrayLength,
            100 => GetField,
            101 => SetField,
            102 => GetStatic,
            103 => SetStatic,
            110 => InvokeStatic,
            111 => InvokeInstance,
            112 => InvokeSpecial,
            113 => InvokeClosure,
            114 => Return,
            115 => ReturnValue,
            120 => StrConcat,
            130 => Throw,
            _ => return None,
        };
        Some(op)
    }
}
