//! Tokens — see nlvm-specs/docs/specs.md § Keywords, § Identifiers, § Operators.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Keyword {
    If,
    Else,
    While,
    For,
    Break,
    Continue,
    Switch,
    Case,
    Default,
    Match,
    Auto,
    Const,
    Ref,
    Void,
    True,
    False,
    Null,
    Return,
    Undefined,
    Class,
    Interface,
    Namespace,
    Extends,
    Implements,
    This,
    Super,
    SelfType,
    TypeKw,
    Use,
    As,
    Instanceof,
    Private,
    Public,
    Protected,
    Static,
    Final,
    Abstract,
    Readonly,
    Nodiscard,
    Template,
    Operator,
    Try,
    Catch,
    Finally,
    Throw,
    Throws,
    Construct,
    Destruct,
    New,
    Enum,
    Typedef,
}

impl Keyword {
    pub fn lookup(ident: &str) -> Option<Keyword> {
        use Keyword::*;
        Some(match ident {
            "if" => If,
            "else" => Else,
            "while" => While,
            "for" => For,
            "break" => Break,
            "continue" => Continue,
            "switch" => Switch,
            "case" => Case,
            "default" => Default,
            "match" => Match,
            "auto" => Auto,
            "const" => Const,
            "ref" => Ref,
            "void" => Void,
            "true" => True,
            "false" => False,
            "null" => Null,
            "return" => Return,
            "undefined" => Undefined,
            "class" => Class,
            "interface" => Interface,
            "namespace" => Namespace,
            "extends" => Extends,
            "implements" => Implements,
            "this" => This,
            "super" => Super,
            "Self" => SelfType,
            "type" => TypeKw,
            "use" => Use,
            "as" => As,
            "instanceof" => Instanceof,
            "private" => Private,
            "public" => Public,
            "protected" => Protected,
            "static" => Static,
            "final" => Final,
            "abstract" => Abstract,
            "readonly" => Readonly,
            "nodiscard" => Nodiscard,
            "template" => Template,
            "operator" => Operator,
            "try" => Try,
            "catch" => Catch,
            "finally" => Finally,
            "throw" => Throw,
            "throws" => Throws,
            "construct" => Construct,
            "destruct" => Destruct,
            "new" => New,
            "enum" => Enum,
            "typedef" => Typedef,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Punct {
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Semi,
    Comma,
    Dot,
    Colon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Assign,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    EqEq,
    NotEq,
    Lt,
    Gt,
    Le,
    Ge,
    AndAnd,
    OrOr,
    Not,
    Question,
    QuestionQuestion,
    QuestionColon,
    Arrow,
    PlusPlus,
    MinusMinus,
    Spaceship,
    Pipe,
    Amp,
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Ident(String),
    Keyword(Keyword),
    IntLiteral(i64),
    FloatLiteral(f64),
    StringLiteral(String),
    Punct(Punct),
    Eof,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub line: u32,
}
